In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
filenames = ['./season_20.csv', './season_19.csv', './season_18.csv']

csv = pd.read_csv(filenames[0])
csv

,name,wins,apps,win ratio,9/12/2019,16/12/2019,6/1/2019,20/1/2020,27/1/2020,3/2/2020,...,17/8/2020,24/8/2020,31/8/2020,7/9/2020,14/9/2020,21/9/2020,28/9/2020,5/10/2020,12/10/2020,7/12/2020
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Darren,15.0,21.0,71.43%,0.0,0.5,1.0,0.0,1.0,1.0,...,0.0,NaN,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0
2,Mark,7.0,22.0,31.82%,1.0,0.5,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Paul,7.0,19.0,36.84%,1.0,0.5,NaN,NaN,1.0,1.0,...,0.0,NaN,1.0,0.0,0.0,NaN,0.0,0.0,0.0,1.0
4,Eoin Delaney,2.0,3.0,66.67%,NaN,NaN,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Conor Kk,10.0,20.0,50.00%,0.0,0.5,1.0,1.0,0.0,0.0,...,NaN,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0
6,Clarkey,10.0,20.0,50.00%,0.0,0.5,NaN,0.0,1.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0
7,Gav,8.5,16.0,53.13%,1.0,0.5,1.0,1.0,0.0,0.0,...,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0
8,Tim,8.5,22.0,38.64%,1.0,NaN,0.0,1.0,1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9,Conor Mc,15.0,21.0,71.43%,1.0,0.5,1.0,NaN,NaN,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0
10,Jonie,4.0,15.0,26.67%,0.0,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,1.0,0.0
11,Greener,7.0,17.0,41.18%,0.0,0.5,NaN,0.0,0.0,0.0,...,NaN,1.0,0.0,0.0,1.0,NaN,NaN,1.0,1.0,0.0
12,Owen Merry,4.5,6.0,75.00%,NaN,NaN,0.0,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Andy Ricci,1.5,2.0,75.00%,NaN,0.5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
14,Peter Hogan,6.0,10.0,60.00%,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.0,NaN,0.0,0.0,1.0,1.0,NaN
15,Conor J,2.0,2.0,100.00%,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
16,NaN,0.0,0.0,#DIV/0!,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,0.0,0.0,#DIV/0!,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,0.0,0.0,#DIV/0!,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,0.0,0.0,#DIV/0!,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
total_player_list = []
flipped_dfs = []

for filename in filenames:
    csv = pd.read_csv(filename)

    # remove rows and columns we don't need
    cleaned_csv = csv.dropna(subset=['name'])
    cleaned_csv = cleaned_csv.drop(['wins', 'apps', 'win ratio'], 1)

    #flip it to be the way we want
    flipped = cleaned_csv.set_index('name').transpose()

    #drop date column for now (has been renamed 'name' in the flip)
    # I might use this in future work, but not now
    flipped_dfs.append(flipped)
    total_player_list = total_player_list + list(flipped.columns)

total_player_list = list(set(total_player_list)) # make to a unique list

print(total_player_list)

## Add to each frame, so that they all have the same columns
for fd in flipped_dfs:
    for name in total_player_list:
        if name not in list(fd.columns):
            fd.insert(len(fd.columns), name, [float("NaN")] * len(fd), True) 
    
flipped_dfs

flipped = pd.concat(flipped_dfs)
flipped

['Andy Ricci', 'Peter Hogan', 'Duffer', 'Mark', 'Sean Douglas', 'big Dave', 'Conor Kk', 'Barron', 'Darren', 'Clarkey', 'Gav', 'Greener', 'Pascal', 'Jonie', 'Conor J', 'Josh', 'Tom', 'Conor Mc', 'Eoin Delaney', 'Owen Merry', 'Tim', 'Dylan', 'Paul', 'Owen greenersfriend']

,Darren,Mark,Paul,Eoin Delaney,Conor Kk,Clarkey,Gav,Tim,Conor Mc,Jonie,...,Conor J,Duffer,Sean Douglas,big Dave,Barron,Pascal,Josh,Tom,Dylan,Owen greenersfriend
9/12/2019,0.0,1.0,1.0,NaN,0.0,0.0,1.0,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16/12/2019,0.5,0.5,0.5,NaN,0.5,0.5,0.5,NaN,0.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6/1/2019,1.0,1.0,NaN,0.0,1.0,NaN,1.0,0.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20/1/2020,0.0,1.0,NaN,NaN,1.0,0.0,1.0,1.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27/1/2020,1.0,0.0,1.0,NaN,0.0,1.0,0.0,1.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5/11/2018,NaN,1.0,0.0,1.0,NaN,1.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
19/11/2018,0.0,1.0,NaN,1.0,1.0,0.0,1.0,1.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
26/11/2018,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3/12/2018,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10/12/2018,1.0,1.0,0.0,NaN,0.0,1.0,0.0,0.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN

In [4]:
player_names = list(flipped.columns) 
player_names

['Darren',
 'Mark',
 'Paul',
 'Eoin Delaney',
 'Conor Kk',
 'Clarkey',
 'Gav',
 'Tim',
 'Conor Mc',
 'Jonie',
 'Greener',
 'Owen Merry',
 'Andy Ricci',
 'Peter Hogan',
 'Conor J',
 'Duffer',
 'Sean Douglas',
 'big Dave',
 'Barron',
 'Pascal',
 'Josh',
 'Tom',
 'Dylan',
 'Owen greenersfriend']

In [5]:
RANDOMER = "Randomer"

def formRandomerName(num: int) -> str:
    return RANDOMER + str(num)
    

## work out how many randomers we need

totals = []
for index, row in flipped.iterrows():
    losers = list(row.array).count(0)
    winners = list(row.array).count(1)
    drawers =  list(row.array).count(0.5)
    total_players = losers + winners + drawers
    totals.append(total_players)

print("average players per game: %f" % (sum(totals)/len(totals)))
min_players = min(totals)
randomers_needed = 10-min_players
print("Minimum numbers of players present in a game: %i" % min_players)
print("Maximum number of randomers in a game: %i" % randomers_needed)

for i in range(randomers_needed):
    randomer_name =  formRandomerName(i)
    flipped[randomer_name] = float("NaN")


# Now populate results for these randomers
for index, row in flipped.iterrows():
    losers = list(row.array).count(0)
    winners = list(row.array).count(1)
    drawers =  list(row.array).count(0.5)
    total_players = losers + winners + drawers
    totals.append(total_players)
    
    randomer_index = 0
    if drawers != 0:
        for i in range(10-drawers):
            randomer_name =  formRandomerName(randomer_index)
            row[randomer_name] = 0.5
            randomer_index+=1
        continue #If its a draw, there should be no winners or losers

    for i in range(5-winners):
        randomer_name =  formRandomerName(randomer_index)
        row[randomer_name] = 1
        randomer_index+=1
        
    for i in range(5-losers):
        randomer_name =  formRandomerName(randomer_index)
        row[randomer_name] = 0
        randomer_index+=1
        
# Check that everything sums up ok, print if it doesn't
for index, row in flipped.iterrows():
    losers = list(row.array).count(0)
    winners = list(row.array).count(1)
    drawers =  list(row.array).count(0.5)
    total_players = losers + winners + drawers
    if total_players != 10:
        print(row)

player_names = list(flipped.columns) 
        
flipped

average players per game: 9.432099
Minimum numbers of players present in a game: 3
Maximum number of randomers in a game: 7

,Darren,Mark,Paul,Eoin Delaney,Conor Kk,Clarkey,Gav,Tim,Conor Mc,Jonie,...,Tom,Dylan,Owen greenersfriend,Randomer0,Randomer1,Randomer2,Randomer3,Randomer4,Randomer5,Randomer6
9/12/2019,0.0,1.0,1.0,NaN,0.0,0.0,1.0,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16/12/2019,0.5,0.5,0.5,NaN,0.5,0.5,0.5,NaN,0.5,NaN,...,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN
6/1/2019,1.0,1.0,NaN,0.0,1.0,NaN,1.0,0.0,1.0,NaN,...,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN
20/1/2020,0.0,1.0,NaN,NaN,1.0,0.0,1.0,1.0,NaN,0.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
27/1/2020,1.0,0.0,1.0,NaN,0.0,1.0,0.0,1.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5/11/2018,NaN,1.0,0.0,1.0,NaN,1.0,0.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19/11/2018,0.0,1.0,NaN,1.0,1.0,0.0,1.0,1.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26/11/2018,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3/12/2018,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10/12/2018,1.0,1.0,0.0,NaN,0.0,1.0,0.0,0.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
import math
import random

def is_picked(value: float, winning_team: bool) -> float:
    if math.isnan(value):
        return 0.0
    if value == 0.5:
        #draw game, we will assign these later
        return value
    if winning_team:
        return value
    else:
        return 1-value
            

# we call the winners the white team, and the losers the black team
for player in player_names:
    flipped[player+'_white'] = flipped[player].apply(lambda x:is_picked(x, True))
    flipped[player+'_black'] = flipped[player].apply(lambda x:is_picked(x, False))

#show how we decomposed this
flipped[['Paul', 'Paul_white', 'Paul_black']]

            Paul  Paul_white  Paul_black
9/12/2019    1.0         1.0         0.0
16/12/2019   0.5         0.5         0.5
6/1/2019     NaN         0.0         0.0
20/1/2020    NaN         0.0         0.0
27/1/2020    1.0         1.0         0.0
...          ...         ...         ...
5/11/2018    0.0         0.0         1.0
19/11/2018   NaN         0.0         0.0
26/11/2018   1.0         1.0         0.0
3/12/2018    1.0         1.0         0.0
10/12/2018   0.0         0.0         1.0

[81 rows x 3 columns]

In [7]:
def get_result(row):
    if 0.5 in list(row):
        return 0.5
    else:
        return 1.0


#add result. These are all white wins, unless they are draws
flipped['result'] = flipped.apply(get_result , axis=1)


flipped[['Paul', 'Paul_white', 'Paul_black', 'result']]

            Paul  Paul_white  Paul_black  result
9/12/2019    1.0         1.0         0.0     1.0
16/12/2019   0.5         0.5         0.5     0.5
6/1/2019     NaN         0.0         0.0     1.0
20/1/2020    NaN         0.0         0.0     1.0
27/1/2020    1.0         1.0         0.0     1.0
...          ...         ...         ...     ...
5/11/2018    0.0         0.0         1.0     1.0
19/11/2018   NaN         0.0         0.0     1.0
26/11/2018   1.0         1.0         0.0     1.0
3/12/2018    1.0         1.0         0.0     1.0
10/12/2018   0.0         0.0         1.0     1.0

[81 rows x 4 columns]

In [8]:
#fill in draws, randomly picking teams, as we don't have this info
import random

for index in flipped.index:
    if flipped.loc[index,'result'] == 0.5:
        white_players = 0
        #pick 5 guys who were there for white team
        while white_players < 5:
            player = random.choice(player_names)
            if flipped.loc[index, player+'_white'] == 0.5:
                flipped.loc[index, player+'_white'] = 1.0
                flipped.loc[index, player+'_black'] = 0.0
                white_players += 1
        #put all the others playing into the black team
        for player in player_names:
            if flipped.loc[index, player+'_black'] == 0.5:
                flipped.loc[index, player+'_white'] = 0.0
                flipped.loc[index, player+'_black'] = 0.1
                white_players += 1
            
print(flipped[['Paul', 'Paul_white', 'Paul_black', 'result']])

flipped

            Paul  Paul_white  Paul_black  result
9/12/2019    1.0         1.0         0.0     1.0
16/12/2019   0.5         0.0         0.1     0.5
6/1/2019     NaN         0.0         0.0     1.0
20/1/2020    NaN         0.0         0.0     1.0
27/1/2020    1.0         1.0         0.0     1.0
...          ...         ...         ...     ...
5/11/2018    0.0         0.0         1.0     1.0
19/11/2018   NaN         0.0         0.0     1.0
26/11/2018   1.0         1.0         0.0     1.0
3/12/2018    1.0         1.0         0.0     1.0
10/12/2018   0.0         0.0         1.0     1.0

[81 rows x 4 columns]

,Darren,Mark,Paul,Eoin Delaney,Conor Kk,Clarkey,Gav,Tim,Conor Mc,Jonie,...,Randomer2_black,Randomer3_white,Randomer3_black,Randomer4_white,Randomer4_black,Randomer5_white,Randomer5_black,Randomer6_white,Randomer6_black,result
9/12/2019,0.0,1.0,1.0,NaN,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16/12/2019,0.5,0.5,0.5,NaN,0.5,0.5,0.5,NaN,0.5,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5
6/1/2019,1.0,1.0,NaN,0.0,1.0,NaN,1.0,0.0,1.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
20/1/2020,0.0,1.0,NaN,NaN,1.0,0.0,1.0,1.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
27/1/2020,1.0,0.0,1.0,NaN,0.0,1.0,0.0,1.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5/11/2018,NaN,1.0,0.0,1.0,NaN,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19/11/2018,0.0,1.0,NaN,1.0,1.0,0.0,1.0,1.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
26/11/2018,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3/12/2018,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10/12/2018,1.0,1.0,0.0,NaN,0.0,1.0,0.0,0.0,1.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [12]:
## WEATHER

from src.weather.weather_service import WeatherService
from datetime import datetime, timedelta

FORMAT = '%d/%m/%Y %H:%M'

BELFIELD_LATITUDE = 53.3067
BELFIELD_LONGITUDE = -6.2210


weather_service = WeatherService(BELFIELD_LATITUDE, BELFIELD_LONGITUDE)
weather_service.set_station("03969")

def formStartEndTimes(datestr: str):
    if datestr[2] != '/':
        datestr = '0' + datestr
    if datestr[5] != '/':
        datestr = datestr[0:3] +'0' + datestr[3:]
    
    datestr = datestr + ' 21:00' # our matches have always started at 9pm
    start = datetime.strptime(datestr, FORMAT)

    end = start + timedelta(hours=1)

    return start, end
    

def getRainfall(row):
    datestr = row.name
    start, end = formStartEndTimes(datestr)
    weather = weather_service.get_weather(start, end)
    return weather.rain

flipped['rainfall'] = flipped.apply(getRainfall, axis=1)

print(rainfall)

9/12/2019     0.0
16/12/2019    0.0
6/1/2019      0.0
20/1/2020     0.0
27/1/2020     0.0
             ...
5/11/2018     0.2
19/11/2018    0.0
26/11/2018    0.0
3/12/2018     0.0
10/12/2018    0.0
Length: 81, dtype: float64

In [13]:
#drop originals
white_wins = flipped.drop(player_names, 1)

In [14]:
#make black wins dataset, which are the same results, but with the labels flipped, and black always winning
# this is important to make sure the algo doesn't always think that the white team wins every time!!!

mapping = {}
for player in player_names:
    mapping[player+ '_white'] = player + '_black'
    mapping[player+ '_black'] = player + '_white'
        

black_wins = white_wins.rename(columns=mapping)
black_wins['result'] = black_wins['result'].apply(lambda x:1-x)

black_wins

,Darren_black,Darren_white,Mark_black,Mark_white,Paul_black,Paul_white,Eoin Delaney_black,Eoin Delaney_white,Conor Kk_black,Conor Kk_white,...,Randomer3_black,Randomer3_white,Randomer4_black,Randomer4_white,Randomer5_black,Randomer5_white,Randomer6_black,Randomer6_white,result,rainfall
9/12/2019,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16/12/2019,0.0,0.1,1.0,0.0,0.0,0.1,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0
6/1/2019,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20/1/2020,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27/1/2020,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5/11/2018,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2
19/11/2018,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26/11/2018,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3/12/2018,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10/12/2018,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
combined = pd.concat([white_wins, black_wins])

#index has  dupes after the combine, need to remove these
combined.index = range(len(combined))
combined

,Darren_white,Darren_black,Mark_white,Mark_black,Paul_white,Paul_black,Eoin Delaney_white,Eoin Delaney_black,Conor Kk_white,Conor Kk_black,...,Randomer3_white,Randomer3_black,Randomer4_white,Randomer4_black,Randomer5_white,Randomer5_black,Randomer6_white,Randomer6_black,result,rainfall
0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.1,1.0,0.0,0.0,0.1,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0
2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2
158,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
159,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
160,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
161,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
## Verify that there are no Nans in the frame, as this will cause serious issues

for col in list(combined.columns):
    print(col +
    " type: " + str(combined.dtypes[col]) +
    " Nan count: " + str(combined[col].isna().sum()))

Darren_white type: float64 Nan count: 0
Darren_black type: float64 Nan count: 0
Mark_white type: float64 Nan count: 0
Mark_black type: float64 Nan count: 0
Paul_white type: float64 Nan count: 0
Paul_black type: float64 Nan count: 0
Eoin Delaney_white type: float64 Nan count: 0
Eoin Delaney_black type: float64 Nan count: 0
Conor Kk_white type: float64 Nan count: 0
Conor Kk_black type: float64 Nan count: 0
Clarkey_white type: float64 Nan count: 0
Clarkey_black type: float64 Nan count: 0
Gav_white type: float64 Nan count: 0
Gav_black type: float64 Nan count: 0
Tim_white type: float64 Nan count: 0
Tim_black type: float64 Nan count: 0
Conor Mc_white type: float64 Nan count: 0
Conor Mc_black type: float64 Nan count: 0
Jonie_white type: float64 Nan count: 0
Jonie_black type: float64 Nan count: 0
Greener_white type: float64 Nan count: 0
Greener_black type: float64 Nan count: 0
Owen Merry_white type: float64 Nan count: 0
Owen Merry_black type: float64 Nan count: 0
Andy Ricci_white type: float64 Nan count: 0
Andy Ricci_black type: float64 Nan count: 0
Peter Hogan_white type: float64 Nan count: 0
Peter Hogan_black type: float64 Nan count: 0
Conor J_white type: float64 Nan count: 0
Conor J_black type: float64 Nan count: 0
Duffer_white type: float64 Nan count: 0
Duffer_black type: float64 Nan count: 0
Sean Douglas_white type: float64 Nan count: 0
Sean Douglas_black type: float64 Nan count: 0
big Dave_white type: float64 Nan count: 0
big Dave_black type: float64 Nan count: 0
Barron_white type: float64 Nan count: 0
Barron_black type: float64 Nan count: 0
Pascal_white type: float64 Nan count: 0
Pascal_black type: float64 Nan count: 0
Josh_white type: float64 Nan count: 0
Josh_black type: float64 Nan count: 0
Tom_white type: float64 Nan count: 0
Tom_black type: float64 Nan count: 0
Dylan_white type: float64 Nan count: 0
Dylan_black type: float64 Nan count: 0
Owen greenersfriend_white type: float64 Nan count: 0
Owen greenersfriend_black type: float64 Nan count: 0
Randomer0_white type: float64 Nan count: 0
Randomer0_black type: float64 Nan count: 0
Randomer1_white type: float64 Nan count: 0
Randomer1_black type: float64 Nan count: 0
Randomer2_white type: float64 Nan count: 0
Randomer2_black type: float64 Nan count: 0
Randomer3_white type: float64 Nan count: 0
Randomer3_black type: float64 Nan count: 0
Randomer4_white type: float64 Nan count: 0
Randomer4_black type: float64 Nan count: 0
Randomer5_white type: float64 Nan count: 0
Randomer5_black type: float64 Nan count: 0
Randomer6_white type: float64 Nan count: 0
Randomer6_black type: float64 Nan count: 0
result type: float64 Nan count: 0
rainfall type: float64 Nan count: 0

In [17]:
target = combined.pop('result')
target

0      1.0
1      0.5
2      1.0
3      1.0
4      1.0
      ...
157    0.0
158    0.0
159    0.0
160    0.0
161    0.0
Name: result, Length: 162, dtype: float64

In [18]:
dataset = tf.data.Dataset.from_tensor_slices((combined.values, target.values))

for feat, targ in dataset.take(5):
  print ('Features: {}, Target: {}'.format(feat, targ))

dataset = dataset.shuffle(len(combined)).batch(1)

## Need to maximise our training dataset, so we just use a subset for validation
train_size = int(0.9 * len(dataset))

train_dataset = dataset
val_dataset = dataset.skip(train_size)

print("Total rows: " + str(len(dataset)))
print("Training set: " + str(len(train_dataset)))
print("Validation set: " + str(len(val_dataset)))

Features: [0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], Target: 1.0
Features: [0.  0.1 1.  0.  0.  0.1 0.  0.  1.  0.  1.  0.  0.  0.1 0.  0.  1.  0.
 0.  0.  1.  0.  0.  0.  0.  0.1 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.1 0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0. ], Target: 0.5
Features: [1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], Target: 1.0
Features: [0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], Target: 1.0
Features: [1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], Target: 1.0
Total rows: 162
Training set: 162
Validation set: 17

In [19]:
tf.keras.backend.set_floatx('float64')

def get_compiled_model():
  model = tf.keras.Sequential([
    tf.keras.layers.Dense(20, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1)
  ])

  model.compile(optimizer='adam',
                loss=tf.keras.losses.MeanSquaredError() ,
                metrics=['accuracy'])
  return model

model = get_compiled_model()
model.fit(train_dataset,validation_data=val_dataset, epochs=12)

Epoch 1/12
162/162 [==============================] - 0s 2ms/step - loss: 0.3727 - accuracy: 0.4877 - val_loss: 0.2357 - val_accuracy: 0.5882
Epoch 2/12
162/162 [==============================] - 0s 917us/step - loss: 0.2258 - accuracy: 0.5494 - val_loss: 0.1948 - val_accuracy: 0.5294
Epoch 3/12
162/162 [==============================] - 0s 979us/step - loss: 0.2046 - accuracy: 0.5802 - val_loss: 0.1378 - val_accuracy: 0.6471
Epoch 4/12
162/162 [==============================] - 0s 924us/step - loss: 0.1834 - accuracy: 0.6543 - val_loss: 0.1233 - val_accuracy: 0.6471
Epoch 5/12
162/162 [==============================] - 0s 960us/step - loss: 0.1656 - accuracy: 0.6667 - val_loss: 0.1459 - val_accuracy: 0.7059
Epoch 6/12
162/162 [==============================] - 0s 973us/step - loss: 0.1549 - accuracy: 0.6975 - val_loss: 0.1311 - val_accuracy: 0.7647
Epoch 7/12
162/162 [==============================] - 0s 973us/step - loss: 0.1423 - accuracy: 0.7222 - val_loss: 0.1998 - val_accuracy: 0.5882
Epoch 8/12
162/162 [==============================] - 0s 997us/step - loss: 0.1288 - accuracy: 0.7469 - val_loss: 0.0849 - val_accuracy: 0.8824
Epoch 9/12
162/162 [==============================] - 0s 1ms/step - loss: 0.1209 - accuracy: 0.7654 - val_loss: 0.1171 - val_accuracy: 0.8235
Epoch 10/12
162/162 [==============================] - 0s 1ms/step - loss: 0.1105 - accuracy: 0.7778 - val_loss: 0.0869 - val_accuracy: 0.8235
Epoch 11/12
162/162 [==============================] - 0s 966us/step - loss: 0.1012 - accuracy: 0.7901 - val_loss: 0.1074 - val_accuracy: 0.8235
Epoch 12/12
162/162 [==============================] - 0s 1ms/step - loss: 0.0946 - accuracy: 0.7901 - val_loss: 0.0769 - val_accuracy: 0.8824

In [20]:
from src.team_selection import TeamSelection
from src.potential_selections_generator import generate_all_possible_selections

##pick all possible team combinations for testing

tonights_players = ['Darren',
 'Peter Hogan',
 'Paul',
 'Conor Kk',
 'Clarkey',
 'Gav',
 'Tim',
 'Conor Mc',
 'Conor J',
 'Greener']

potential_selections = generate_all_possible_selections(tonights_players)


print("Number of potential different combinations: %i" % len(potential_selections))

Number of potential different combinations: 252

In [23]:
most_fair = None
biggest_white = None
biggest_black = None

blank_table = combined[0:0]

for selection in potential_selections:
    input = blank_table.copy()
    input = input.append(pd.Series(0, index=input.columns), ignore_index=True)
    for white_player in selection.white:
        input[white_player + '_white'] = 1.0
    for black_player in selection.black:
        input[black_player + '_black'] = 1.0
        
    ## Set weather
    input['rainfall'] = 0.0
    
    selection.rating = model.predict(input.values)
    
    if (most_fair == None) or (abs(selection.rating - 0.5) < abs(most_fair.rating - 0.5)):
        most_fair = selection
        
    if (biggest_white == None) or (selection.rating > biggest_white.rating):
        biggest_white = selection
        
    if (biggest_black == None) or (selection.rating < biggest_black.rating):
        biggest_black = selection
        

print('Fairest')
print(most_fair)
print(most_fair.rating)

print('Largest white victory')
print(biggest_white)
print(biggest_white.rating)

print('Largest black victory')
print(biggest_black)
print(biggest_black.rating)

Fairest
white team: ['Paul', 'Conor Kk', 'Gav', 'Tim', 'Conor Mc'], black team: ['Darren', 'Peter Hogan', 'Clarkey', 'Conor J', 'Greener']
[[0.5013801]]
Largest white victory
white team: ['Darren', 'Peter Hogan', 'Paul', 'Conor Kk', 'Conor Mc'], black team: ['Clarkey', 'Gav', 'Tim', 'Conor J', 'Greener']
[[1.3023119]]
Largest black victory
white team: ['Paul', 'Gav', 'Tim', 'Conor J', 'Greener'], black team: ['Darren', 'Peter Hogan', 'Conor Kk', 'Clarkey', 'Conor Mc']
[[-0.01808726]]